# Generated by Django 4.2.7 on 2023-11-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_Staff',
            new_name='is_staff',
        ),
    ]
